### ISSUE TITLE
Build service certificate error.

### ISSUE THREAD

**Issue by aminecmi** [AppGyver/build-service#45]
There is an issue with the build service for IOS as described in [this post](http://forum.appgyver.com/t/ios-build-error-detected-incorrect-certificate-errors/5818/3)

The build service worked fine last week, and now, there is a certificate error.

**Comment by xune3** [comment]
same here, seems like there is a problem with the Apple Intermediate Certificate on the build service itself. the certificate's expiration date is the 14th of february 2016.. so yesterday.. the new certificate is valid until february 2023.. so can anyone with access to the build service update those intermediate certificates on the system?

**Comment by aminecmi** [comment]
[response here](https://github.com/AppGyver/steroids/issues/332#issuecomment-184168475)

**Comment by harsaharsa** [comment]
This should now be fixed. Let us know if any problems persist!
